version: '2'
services:
    referentielapplication-app:
        image: referentielapplication
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://referentielapplication-postgresql:5432/referentielApplication
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_JEST_URI=http://referentielapplication-elasticsearch:9200
        ports:
            - 8080:8080
    referentielapplication-postgresql:
        extends:
            file: postgresql.yml
            service: referentielapplication-postgresql
    referentielapplication-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: referentielapplication-elasticsearch
